---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: content
  label: Content
  create: all
  match: "**/*"
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - CTF_SPACE_ID=s54fg9ycsdnw
  - CTF_CDA_ACCESS_TOKEN=3rczcfkfA_SsAFZ7Z1KNF8P0vRJK8CiH0NVpVCmYTo0
  preview_output_directory: dist
  install_dependencies_command: yarn
  preview_docker_image: forestryio/node:16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn dev
